# Load Library

In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Load Dataset

In [2]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

# View Movie Dataset

In [3]:
movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

# View Credit Dataset

In [4]:
credits.head(3)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

# show column name of movie and credits datset

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [6]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [7]:
movies.shape

(4803, 20)

In [8]:
credits.shape

(4803, 4)

In [9]:
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [10]:
credits.describe()

            movie_id
count    4803.000000
mean    57165.484281
std     88694.614033
min         5.000000
25%      9014.500000
50%     14629.000000
75%     58610.500000
max    459488.000000

# Merge Datset on title column basis

In [11]:
movies = movies.merge(credits,on='title')

In [12]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [13]:
# budget
# homepage
# id
# original_language
# original_title
# popularity
# production_comapny
# production_countries
# release-date(not sure)
# all these column not necessary for our model so drop these columns
movies = movies[['movie_id','title','homepage','vote_average','vote_count','overview','genres','keywords','cast','crew','release_date']]

In [14]:
movies.head()

,movie_id,title,homepage,vote_average,vote_count,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,http://www.avatarmovie.com/,7.2,11800,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10
1,285,Pirates of the Caribbean: At World's End,http://disney.go.com/disneypictures/pirates/,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19
2,206647,Spectre,http://www.sonypictures.com/movies/spectre/,6.3,4466,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",2015-10-26
3,49026,The Dark Knight Rises,http://www.thedarkknightrises.com/,7.6,9106,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",2012-07-16
4,49529,John Carter,http://movies.disney.com/john-carter,6.1,2124,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",2012-03-07

# Data Cleaning

In [15]:
import ast   #load ast(abstract syntax tree) for convert list into string

In [16]:
def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

# Drop Na Row

In [17]:
movies.dropna(inplace=True)

## convert list of dictionary into list

In [18]:
movies['genres'] = movies['genres'].apply(convert)
movies['keywords'] = movies['keywords'].apply(convert)
movies['cast'] = movies['cast'].apply(convert)
movies.head()

,movie_id,title,homepage,vote_average,vote_count,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,http://www.avatarmovie.com/,7.2,11800,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2009-12-10
1,285,Pirates of the Caribbean: At World's End,http://disney.go.com/disneypictures/pirates/,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",2007-05-19
2,206647,Spectre,http://www.sonypictures.com/movies/spectre/,6.3,4466,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",2015-10-26
3,49026,The Dark Knight Rises,http://www.thedarkknightrises.com/,7.6,9106,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",2012-07-16
4,49529,John Carter,http://movies.disney.com/john-carter,6.1,2124,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",2012-03-07

##  Get Top 3 crew name

In [19]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [20]:
def convert3(text):
    L = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter < 3:
            L.append(i['name'])
        counter+=1
    return L

In [21]:
movies['cast'] = movies['cast'].apply(lambda x:x[0:3])

## Get director name from crew

In [22]:
def fetch_director(text):
    L = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            L.append(i['name'])
    return L

In [23]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [24]:
movies.sample(5)

,movie_id,title,homepage,vote_average,vote_count,overview,genres,keywords,cast,crew,release_date
893,26389,From Paris with Love,http://www.frompariswithlovefilm.com/,6.1,675,James Reese has a good job as an ambassador's ...,"[Action, Crime, Thriller]","[paris, cia, undercover, explosive, pimp, amba...","[John Travolta, Jonathan Rhys Meyers, Kasia Sm...",[Pierre Morel],2010-02-05
3753,241251,The Boy Next Door,http://www.theboynextdoorfilm.com/,4.1,1022,A recently cheated on married woman falls for ...,[Thriller],"[male nudity, female nudity, sex, adultery, in...","[Jennifer Lopez, Ryan Guzman, Ian Nelson]",[Rob Cohen],2015-01-23
3685,1690,Hostel,http://www.hostelfilm.com/,5.7,887,Three backpackers head to a Slovakian city tha...,[Horror],"[bathroom, sex, amsterdam, europe, brothel, sl...","[Jay Hernandez, Derek Richardson, Eythor Gudjo...",[Eli Roth],2005-01-06
705,19899,Couples Retreat,http://www.couplesretreatmovie.com/,5.3,588,"Four couples, all friends, descend on a tropic...","[Comedy, Romance]","[island, married couple, yoga, tahiti, couples...","[Vince Vaughn, Malin Åkerman, Jason Bateman]",[Peter Billingsley],2009-09-19
1725,3638,No Reservations,http://noreservationsmovie.warnerbros.com/,6.1,327,Master chef Kate Armstrong runs her life and h...,[Comedy],"[italy, competition, loss of mother, loss of s...","[Catherine Zeta-Jones, Aaron Eckhart, Abigail ...",[Scott Hicks],2007-07-25

In [25]:
#handle space between words
def collapse(L):
    L1 = []
    for i in L:
        L1.append(i.replace(" ",""))
    return L1

In [26]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [27]:
movies.head()

,movie_id,title,homepage,vote_average,vote_count,overview,genres,keywords,cast,crew,release_date
0,19995,Avatar,http://www.avatarmovie.com/,7.2,11800,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],2009-12-10
1,285,Pirates of the Caribbean: At World's End,http://disney.go.com/disneypictures/pirates/,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],2007-05-19
2,206647,Spectre,http://www.sonypictures.com/movies/spectre/,6.3,4466,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],2015-10-26
3,49026,The Dark Knight Rises,http://www.thedarkknightrises.com/,7.6,9106,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],2012-07-16
4,49529,John Carter,http://movies.disney.com/john-carter,6.1,2124,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],2012-03-07

In [28]:
# convert overview string into list
movies['overview'] = movies['overview'].apply(lambda x:x.split())

## create new column Tags

In [29]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']
movies.head(1)

,movie_id,title,homepage,vote_average,vote_count,overview,genres,keywords,cast,crew,release_date,tags
0,19995,Avatar,http://www.avatarmovie.com/,7.2,11800,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],2009-12-10,"[In, the, 22nd, century,, a, paraplegic, Marin..."

## Drop column Genres,keywords,cast and crew

In [30]:
new_movies = movies.drop(columns=['overview','keywords','crew'])

In [31]:
new_movies.head(1)

,movie_id,title,homepage,vote_average,vote_count,genres,cast,release_date,tags
0,19995,Avatar,http://www.avatarmovie.com/,7.2,11800,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",2009-12-10,"[In, the, 22nd, century,, a, paraplegic, Marin..."

## convert tags(list) into strings

In [32]:
new_movies['tags'] = new_movies['tags'].apply(lambda x: " ".join(x))
new_movies.head()

,movie_id,title,homepage,vote_average,vote_count,genres,cast,release_date,tags
0,19995,Avatar,http://www.avatarmovie.com/,7.2,11800,"[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver]",2009-12-10,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,http://disney.go.com/disneypictures/pirates/,6.9,4500,"[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",2007-05-19,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,http://www.sonypictures.com/movies/spectre/,6.3,4466,"[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LéaSeydoux]",2015-10-26,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,http://www.thedarkknightrises.com/,7.6,9106,"[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman]",2012-07-16,Following the death of District Attorney Harve...
4,49529,John Carter,http://movies.disney.com/john-carter,6.1,2124,"[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton]",2012-03-07,"John Carter is a war-weary, former military ca..."

## import countvectorizer class from sklearn library to convert text into vector

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
#get 5000 most frequent word used in tags with stop_words english
cv = CountVectorizer(max_features=5000,stop_words='english')

In [48]:
# list of most frequent 5000 words repeat in tags
cv.get_feature_names()

D:\software\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18th',
 '18thcentury',
 '19',
 '1930s',
 '1937',
 '1940s',
 '1945',
 '1950s',
 '1955',
 '1960s',
 '1964',
 '1967',
 '1970s',
 '1973',
 '1979',
 '1980s',
 '1985',
 '1987',
 '1988',
 '1990s',
 '1995',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '2003',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2016',
 '2019',
 '20th',
 '21stcentury',
 '22nd',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '70',
 'aaron',
 'aaroneckhart',
 'aaronseltzer',
 'aarontaylor',
 'aba',
 'abandoned',
 'abbiecornish',
 'abducted',
 'abigail',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abrams',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'acceptance',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidentally',
 'accompanied',
 'account',
 'accused',
 'achieve',
 'act',
 'action',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'actually',
 'adam',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addiction',
 'adjust',
 'admiration',
 'adolescence',
 'adopted',
 'adoption',
 'adorable',
 'adrift',
 'adult',
 'adultanimation',
 'adultery',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affection',
 'affections',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aging',
 'ago',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airport',
 'aka',
 'al',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'aldous',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'algeria',
 'ali',
 'alice',
 'alicebraga',
 'alien',
 'alieninvasion',
 'alienplanet',
 'aliens',
 'alike',
 'alive',
 'alliance',
 'allied',
 'allies',
 'allow',
 'ally',
 'alongside',
 'alpha',
 'alter',
 'alternate',
 'alternatehistory',
 'alternative',
 'alzheimer',
 'amazing',
 'ambassador',
 'amberheard',
 'ambition',
 'ambitious',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amnesia',
 'amp',
 'amusementpark',
 'amyadams',
 'anakin',
 'analyst',
 'ancient',
 'ancientworld',
 'anderson',
 'andrewgarfield',
 'andrewstanton',
 'android',
 'andy',
 'andyserkis',
 'angel',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'angry',
 'animal',
 'animalattack',
 'animallead',
 'animals',
 'animated',
 'animation',
 'anime',
 'ann',
 'anna',
 'annabelle',
 'annafaris',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'annual',
 'anonymous',
 'answer',
 'answers',
 'ant',
 'antarctic',
 'antarctica',
 'anthony',
 'anthonyhopkins',
 'anthonymackie',
 'anthonyrusso',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antiterror',
 'antonio',
 'antoniobanderas',
 'antonyelchin',
 'anxious',
 'apart',
 'apartheid',
 'apartment',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'appear',
 'appearance',
 'appears',
 'appointed',
 'apprentice',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arbitrarylaw',
 'arcade',
 'arch',
 'archaeologist',
 'archenemy',
 'archeology',
 'archer',
 'archery',
 'architect',
 'area',
 'arena',
 'argument',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnoldschwarzenegger',
 'arrangement',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'arson',
 'art',
 'artgallery',
 'arthur',
 'article',
 'artificial',
 'artificialinsemination',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'asabutterfield',
 'asgard',
 'ash',
 'ashley',
 'ashleytisdale',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asks',
 'asleep',
 'asperger',
 'aspiring',
 'aspiringsinger',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistant',
 'assumes',
 'astronaut',
 'asylum',
 'atheist',
 'athlete',
 'atlanticocean',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attorney',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'auto',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'baby',
 'bachelor',
 'backdrop',
 'backyard',
 'bad',
 'badly',
 'bahamas',
 'bail',
 'balance',
 'ballet',
 'band',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bar',
 'barn',
 'barney',
 'barry',
 'bars',
 'baseball',
 'based',
 'basedonchildren',
 'basedoncomicbook',
 'basedonfairytale',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'beard',
 'bears',
 'beast',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becca',
 'becky',
 'becominganadult',
 'bed',
 'bee',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'bella',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'benjamin',
 'benkingsley',
 'bennet',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlove',
 'beth',
 'bethany',
 'betrayal',
 'betrayed',
 'better',
 'bible',
 'big',
 'biggest',
 'biker',
 'bikini',
 'bilbo',
 'billionaire',
 'billnighy',
 'billpaxton',
 'billy',
 'billybobthornton',
 'billyconnolly',
 'bio',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bite',
 'biting',
 'bitten',
 'bittersweet',
 'bizarre',
 'black',
 'blackandwhite',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blacksmith',
 'blade',
 'blakelively',
 'blame',
 'blart',
 'blast',
 'blending',
 'blind',
 'blizzard',
 'block',
 'blofeld',
 'blog',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blowing',
 'blown',
 'blows',
 'blu',
 'blue',
 'blues',
 'blunt',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'boatchase',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'body',
 'bodyguard',
 'bodyhorror',
 'bohemian',
 'bold',
 'bollywood',
 'bolt',
 'bomb',
 'bombing',
 'bond',
 'bondage',
 'bonds',
 'bone',
 'boo',
 'book',
 'books',
 'boomer',
 'boov',
 'booze',
 'border',
 'borders',
 'bored',
 'borg',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'bourne',
 'bowandarrow',
 'bowling',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boyle',
 'boys',
 'bradbird',
 'bradfurman',
 'bradleycooper',
 'bradpeyton',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'bravery',
 'brazilian',
 'break',
 'breaking',
 'breakingthefourthwall',
 'breaks',
 'breakthrough',
 'breast',
 'breathing',
 'brendan',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brian',
 'briancox',
 'brianrobbins',
 'briantaylor',
 'bride',
 'bridesmaid',
 'bridge',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'britt',
 'broadcasting',
 'brock',
 'broke',
 'broken',
 'brokenhearted',
 'brooklyn',
 'brooklynnewyorkcity',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryan',
 'bryancranston',
 'bryansinger',
 'bryce',
 'brycedallashoward',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bully',
 'bullying',
 'bunker',
 'bunny',
 'burglar',
 'buried',
 'burke',
 'burlesque',
 'burned',
 'bus',
 'bush',
 'business',
 'businessman',
 'businesswoman',
 'bust',
 'busy',
 'butcher',
 'butler',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'caleb',
 'california',
 'called',
 'calls',
 'calvin',
 'cambridge',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candle',
 'candlelightvigil',
 'candy',
 'canine',
 'cannabis',
 'canon',
 'cao',
 'capable',
 'capital',
 'capitalism',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'cardgame',
 'care',
 'career',
 'carefree',
 'carefully',
 'caretaker',
 'carexplosion',
 'careymulligan',
 'cargo',
 'cargoship',
 'caribbean',
 'caring',
 'carjourney',
 'carl',
 'carlagugino',
 'carlossaldanha',
 'carlton',
 'carmen',
 'carnival',
 'carolina',
 'carpet',
 'carrace',
 'carrie',
 'carriefisher',
 'carry',
 'carrying',
 'cars',
 'carsetonfire',
 'carter',
 'cartoon',
 'case',
 'cases',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catacombs',
 'catandmouse',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinehardwicke',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrated',
 'celebration',
 'celebrity',
 'cell',
 'cello',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceo',
 'ceremony',
 'certain',
 'cesar',
 'cgi',
 'chadmichaelmurray',
 'chain',
 'chair',
 'challenge',
 'challenged',
 'challenges',
 'challenging',
 'champion',
 'championship',
 'chance',
 'chaney',
 'change',
 'changed',
 'changes',
 'changing',
 'changingthepastorfuture',
 'channingtatum',
 'chaos',
 'chaotic',
 'chappie',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charges',
 'charismatic',
 'charles',
 'charlesferguson',
 'charlie',
 'charliecox',
 'charlieday',
 'charlizetheron',
 'charm',
 'charming',
 'chase',
 'chases',
 'chasesandraces',
 'cheating',
 'checks',
 'chef',
 'chemical',
 'chest',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'childhoodfriends',
 'childhoodmemory',
 'childlabour',
 'childprodigy',
 'children',
 'chimp',
 'chimps',
 'china',
 'chinese',
 'chipettes',
 'chipmunk',
 'chipmunks',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'choice',
 'choices',
 'choir',
 'choose',
 'chosen',
 'chosenone',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrispine',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christopher',
 'christophermiller',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chronicle',
 'chronicles',
 'chu',
 'church',
 'churchservice',
 'cia',
 'ciaránhinds',
 'cinderella',
 'cindy',
 'cinema',
 'circle',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilization',
 'claim',
 'claims',
 'claire',
 'clan',
 'class',
 'classdifferences',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'clean',
 'client',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closed',
 'closer',
 'closing',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cobra',
 'cocaine',
 'code',
 'codes',
 'coffin',
 'cohen',
 'cold',
 'coldwar',
 'colin',
 'colinfarrell',
 'collapse',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colombia',
 'colony',
 'colorful',
 'coma',
 'combat',
 'combination',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comfort',
 'comic',
 'coming',
 'comingofage',
 'comingout',
 'commander',
 'commitment',
 'committed',
 'common',
 'community',
 'companions',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'compound',
 'computer',
 'concert',
 'condition',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'conman',
 'connection',
 'connell',
 'connor',
 'conquer',
 'consequences',
 'considered',
 'conspiracy',
 'conspiracyofmurder',
 'constantly',
 'contact',
 'contain',
 'containing',
 'contend',
 'contest',
 'continent',
 'continue',
 'continues',
 'contract',
 'contractors',
 'control',
 'controlling',
 'controversial',
 'converge',
 'convict',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 ...]

In [35]:
#convert features names into numpy vetor array
vectors = cv.fit_transform(new_movies['tags']).toarray()

In [36]:
vectors.shape

(1713, 5000)

In [37]:
#import cosine_similarity class to calculate distance between vector
from sklearn.metrics.pairwise import cosine_similarity

In [38]:
similarity = cosine_similarity(vectors)

In [39]:
similarity.shape

(1713, 1713)

In [40]:
# distance of each movie with other movie
similarity

array([[1.        , 0.07938842, 0.05292561, ..., 0.05216405, 0.02250746,
        0.02409813],
       [0.07938842, 1.        , 0.05882353, ..., 0.        , 0.02501564,
        0.        ],
       [0.05292561, 0.05882353, 1.        , ..., 0.        , 0.02501564,
        0.        ],
       ...,
       [0.05216405, 0.        , 0.        , ..., 1.        , 0.04931137,
        0.        ],
       [0.02250746, 0.02501564, 0.02501564, ..., 0.04931137, 1.        ,
        0.06834085],
       [0.02409813, 0.        , 0.        , ..., 0.        , 0.06834085,
        1.        ]])

In [41]:
#get index of movie on movie name
new_movies[new_movies['title'] == 'The Lego Movie'].index[0]

744

## Functiuon return 5 related movie to given movie name on basis of content based filterinng

In [42]:
def recommend(movie):
    index = new_movies[new_movies['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_movies.iloc[i[0]].title)

In [43]:
average_vote_mean=new_movies['vote_average'].mean()
average_vote_mean

6.2449503794512475

In [50]:
def top_rated_movie(mean):
    index = new_movies[new_movies['vote_average'] >= 8.1]
    for i in range(5):
        print(index.iloc[i].title)
        print(index.iloc[i].vote_average)
        print(index.iloc[i].movie_id)
top_rated_movie(average_vote_mean)

The Dark Knight
8.2
155
Interstellar
8.1
157336
Inception
8.1
27205
The Lord of the Rings: The Return of the King
8.1
122
Fight Club
8.3
550

In [45]:
recommend('The Lego Movie')

Disaster Movie
My Name Is Bruce
Feast
Happy Feet Two
Dogma

## import pickle library to dump our model

In [46]:
import pickle

In [49]:
pickle.dump(new_movies,open('movie_list.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))
pickle.dump(new_movies,open('new_movies.pkl','wb'))